name: Enforce PR Branch Rules

on:
  pull_request:
    branches:
      - master
      - testing
      - hotfix

jobs:
  check_master_branch:
    runs-on: ubuntu-latest
    if: github.base_ref == 'master'
    steps:
      - name: Check if PR is from 'testing'
        if: github.head_ref != 'testing' && github.head_ref != 'hotfix'
        run: |
          echo "Pull requests to 'master' are only allowed from 'testing' or 'hotfix'."
          exit 1

  allow_to_testing:
    runs-on: ubuntu-latest
    if: github.base_ref == 'testing' || github.base_ref == 'hotfix'
    steps:
      - name: Allow PR to 'testing'
        run: echo "Pull request to 'testing' allowed."  # Zulässt, dass in "testing" gemerged wird
